# Generated by Django 5.0.3 on 2024-06-07 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(max_length=50, null=True)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('padrenome', models.CharField(max_length=50, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('resume', models.TextField(null=True)),
                ('foto', models.ImageField(blank=True, default='', null=True, upload_to='kss/static/img_author')),
            ],
            options={
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('data', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('format', models.CharField(max_length=10)),
                ('num_pag', models.IntegerField(blank=True, null=True)),
                ('num_aut', models.IntegerField(blank=True, null=True)),
                ('num_art', models.IntegerField(blank=True, null=True)),
                ('num_img', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='', upload_to='kss/static/img_genre')),
            ],
            options={
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='kss/static/img_tipi')),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=10)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('data', models.DateField(blank=True, null=True)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('num_pag', models.IntegerField(blank=True, null=True)),
                ('num_aut', models.IntegerField(blank=True, null=True)),
                ('num_img', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(to='kss.author')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kss.book')),
                ('genre', models.ManyToManyField(help_text='Select a Genre for this storia', to='kss.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ManyToManyField(help_text='Select a Typ for this book', to='kss.type'),
        ),
    ]
