# Generated by Django 5.0.3 on 2024-06-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='birth',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='author',
            name='death',
        ),
    ]
