# Generated by Django 5.0.3 on 2024-06-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0002_rename_birth_author_status_remove_author_death'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'data']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='type',
            new_name='group',
        ),
    ]
