# Generated by Django 5.0.3 on 2024-06-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0004_alter_book_options_book_pseudonym_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['pseudonym', 'title', 'data']},
        ),
        migrations.AddField(
            model_name='article',
            name='pagina_book',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
