# Generated by Django 5.0.3 on 2024-06-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0005_alter_book_options_article_pagina_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['data', 'pseudonym', 'title']},
        ),
        migrations.AddField(
            model_name='type',
            name='pseudonym',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
