# Generated by Django 5.0.3 on 2024-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0007_author_num_art_author_num_img_author_num_pag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
