# Generated by Django 5.0.3 on 2024-06-20 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0008_author_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytle', models.CharField(max_length=50, null=True)),
                ('pagina', models.CharField(max_length=20, null=True)),
                ('pagina_nome', models.CharField(max_length=20, null=True)),
                ('image_pag', models.ImageField(default='', null=True, upload_to='kss/static/img_book_pag')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kss.book')),
            ],
            options={
                'ordering': ['tytle', 'pagina'],
            },
        ),
    ]
