# Generated by Django 5.0.3 on 2024-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0009_bookbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_title',
            field=models.ImageField(default='', null=True, upload_to='kss/static/img_book_title'),
        ),
    ]
