# Generated by Django 5.0.3 on 2024-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0011_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['pseudonym']},
        ),
        migrations.AddField(
            model_name='book',
            name='image_foto',
            field=models.ImageField(default='', null=True, upload_to='kss/static/img_book_foto'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pagina_book',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
