# Generated by Django 5.0.3 on 2024-08-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kss', '0012_alter_type_options_book_image_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the article', max_length=1000),
        ),
    ]
